### ISSUE TITLE
Add a noindex tag in older versions of the documentation

### ISSUE THREAD

**Issue by elisedeux** [Linkurious/documentation#70] opened 2019-03-25 14:05 UTC
Each version of the doc is currently behind indexed by Google, generating multiple URLs pointing toward the doc. This isn't good for SEO nor content optimization.

![Capture](https://user-images.githubusercontent.com/23723610/54925638-f6c8c500-4f0e-11e9-93c5-12e5c0079f5a.PNG)

We need to add [noindex tags](https://support.google.com/webmasters/answer/93710?hl=en) in the older versions of the doc so only the latest version is indexed.

**Comment by davidrapin** [comment] 2019-03-25 19:06
Maybe we should add a "noindex" meta tag in pages not served via the "latest" alias.
Not sure about the best strategy.
We could also generate a robots.txt dynamically.

All in all, that's work for squanchy-server.

**Comment by francescoinfante** [comment] 2019-03-26 10:27
This has been fixed in the squanchy server, I will check in 3 weeks if the problem is solved on google side.
https://github.com/Linkurious/squanchy-server/commit/e55abc345aefc037535dbccd810054ad6bf455ba

**Comment by elisedeux** [comment] 2019-06-11 14:13
I can not reproduce previous results. I think this fixed the problem @francescoinfante.

**Closed** 2019-06-11 16:17 UTC
